name: Firebase Deploy Staging

on:
  push:
    branches:
    - master
    
jobs:
  firebase-deploy-staging:
    name: Building Project

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0
      - name: Use Node.js  
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - name:  Install Packages with Yarn
        run:  yarn
      - name:  Build Project     
        run:  yarn build      
      - name: Deploy to Firebase Staging environment
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --project=staging --only hosting
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
