name: Firebase Deploy Staging

on:
  push:
    branches:
    - master
    
jobs:
  firebase-deploy-staging:
    name: Building Project

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run:  yarn
      - run:  yarn build      
      - uses: w9jds/firebase-action@v1
        with:
          args: deploy --project=staging --only hosting
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
