name: Deploy to Staging environment

on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: Building Project

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build React App and deploy to firebase hosting
        run: |
          yarn
          yarn deploy:stag      

