name: Deploy to Staging environment

on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: Building Project

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build React App and deploy to firebase hosting
      run: yarn deploy:stag

